/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    courses: Course;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'global-sections': GlobalSection;
  };
  globalsSelect: {
    'global-sections': GlobalSectionsSelect<false> | GlobalSectionsSelect<true>;
  };
  locale: 'en' | 'hi';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  hero: number | User;
  sections?:
    | (
        | {
            enabled?: boolean | null;
            heading: string;
            subheading?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSection';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            showCoursePrice?: boolean | null;
            cards?:
              | {
                  planName?: string | null;
                  price?: number | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingSection';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug?: string | null;
  sections?:
    | (
        | {
            enabled?: boolean | null;
            heading: string;
            subheading?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSection';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            showCoursePrice?: boolean | null;
            cards?:
              | {
                  planName?: string | null;
                  price?: number | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingSection';
          }
      )[]
    | null;
  hero?: {
    enabled?: boolean | null;
    heading?: string | null;
    color?: string | null;
  };
  course_hero?: {
    enabled?: boolean | null;
    heading?: string | null;
    color?: string | null;
  };
  logoCarousel?: {
    enabled?: boolean | null;
    heading?: string | null;
    color?: string | null;
  };
  features?: {
    enabled?: boolean | null;
    heading?: string | null;
    color?: string | null;
  };
  how_it_works?: {
    enabled?: boolean | null;
    heading?: string | null;
    color?: string | null;
  };
  comparison_table?: {
    enabled?: boolean | null;
    heading?: string | null;
    color?: string | null;
  };
  reviews?: {
    enabled?: boolean | null;
    heading?: string | null;
    color?: string | null;
  };
  faqs?: {
    enabled?: boolean | null;
    heading?: string | null;
    color?: string | null;
  };
  localSections?:
    | (
        | {
            enabled?: boolean | null;
            heading: string;
            subheading?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSection';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            showCoursePrice?: boolean | null;
            cards?:
              | {
                  planName?: string | null;
                  price?: number | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingSection';
          }
      )[]
    | null;
  localSections1?:
    | (
        | {
            enabled?: boolean | null;
            heading: string;
            subheading?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSection';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            showCoursePrice?: boolean | null;
            cards?:
              | {
                  planName?: string | null;
                  price?: number | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingSection';
          }
      )[]
    | null;
  localSections2?:
    | (
        | {
            enabled?: boolean | null;
            heading: string;
            subheading?: string | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroSection';
          }
        | {
            enabled?: boolean | null;
            title?: string | null;
            showCoursePrice?: boolean | null;
            cards?:
              | {
                  planName?: string | null;
                  price?: number | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingSection';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  highlights?:
    | T
    | {
        text?: T;
        icon?: T;
        id?: T;
      };
  hero?: T;
  sections?:
    | T
    | {
        heroSection?:
          | T
          | {
              enabled?: T;
              heading?: T;
              subheading?: T;
              ctaText?: T;
              ctaLink?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        pricingSection?:
          | T
          | {
              enabled?: T;
              title?: T;
              showCoursePrice?: T;
              cards?:
                | T
                | {
                    planName?: T;
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sections?:
    | T
    | {
        heroSection?:
          | T
          | {
              enabled?: T;
              heading?: T;
              subheading?: T;
              ctaText?: T;
              ctaLink?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        pricingSection?:
          | T
          | {
              enabled?: T;
              title?: T;
              showCoursePrice?: T;
              cards?:
                | T
                | {
                    planName?: T;
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  hero?:
    | T
    | {
        enabled?: T;
        heading?: T;
        color?: T;
      };
  course_hero?:
    | T
    | {
        enabled?: T;
        heading?: T;
        color?: T;
      };
  logoCarousel?:
    | T
    | {
        enabled?: T;
        heading?: T;
        color?: T;
      };
  features?:
    | T
    | {
        enabled?: T;
        heading?: T;
        color?: T;
      };
  how_it_works?:
    | T
    | {
        enabled?: T;
        heading?: T;
        color?: T;
      };
  comparison_table?:
    | T
    | {
        enabled?: T;
        heading?: T;
        color?: T;
      };
  reviews?:
    | T
    | {
        enabled?: T;
        heading?: T;
        color?: T;
      };
  faqs?:
    | T
    | {
        enabled?: T;
        heading?: T;
        color?: T;
      };
  localSections?:
    | T
    | {
        heroSection?:
          | T
          | {
              enabled?: T;
              heading?: T;
              subheading?: T;
              ctaText?: T;
              ctaLink?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        pricingSection?:
          | T
          | {
              enabled?: T;
              title?: T;
              showCoursePrice?: T;
              cards?:
                | T
                | {
                    planName?: T;
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  localSections1?:
    | T
    | {
        heroSection?:
          | T
          | {
              enabled?: T;
              heading?: T;
              subheading?: T;
              ctaText?: T;
              ctaLink?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        pricingSection?:
          | T
          | {
              enabled?: T;
              title?: T;
              showCoursePrice?: T;
              cards?:
                | T
                | {
                    planName?: T;
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  localSections2?:
    | T
    | {
        heroSection?:
          | T
          | {
              enabled?: T;
              heading?: T;
              subheading?: T;
              ctaText?: T;
              ctaLink?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        pricingSection?:
          | T
          | {
              enabled?: T;
              title?: T;
              showCoursePrice?: T;
              cards?:
                | T
                | {
                    planName?: T;
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-sections".
 */
export interface GlobalSection {
  id: number;
  hero?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    highlight?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    subheading?: string | null;
    cta1_Text?: string | null;
    cta2_Text?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  course_hero?: {
    course_hero_eyebrow?: string | null;
    course_hero_heading?: string | null;
    highlight?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    course_hero_subheading?: string | null;
    course_hero_cta1_Text?: string | null;
    course_hero_cta2_Text?: string | null;
  };
  logoCarousel?: {
    enabled?: boolean | null;
    logos?:
      | {
          heading?: string | null;
          subheading?: string | null;
          logo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  features?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    highlight?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    subheading?: string | null;
    features?:
      | {
          heading?: string | null;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  how_it_works?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    highlight?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    subheading?: string | null;
    how_it_works?:
      | {
          heading?: string | null;
          subheading?: string | null;
          description?: string | null;
          btn_text?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  comparison_table?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    highlight?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    subheading?: string | null;
    comparison?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    coaching_center?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    clear_cutoff?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  reviews?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    highlight?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    subheading?: string | null;
    reviews?:
      | {
          name?: string | null;
          profile?: (number | null) | Media;
          gender?: ('male' | 'female') | null;
          field?: string | null;
          review?: string | null;
          rating?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  faqs?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    highlight?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    subheading?: string | null;
    categories?:
      | {
          category?: string | null;
          id?: string | null;
        }[]
      | null;
    faqs?:
      | {
          category?: string | null;
          question?: string | null;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  faqs_yesterday?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    highlight?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    subheading?: string | null;
    categories?:
      | {
          category?: string | null;
          id?: string | null;
        }[]
      | null;
    faqs?:
      | {
          category?: string | null;
          question?: string | null;
          answer?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-sections_select".
 */
export interface GlobalSectionsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        highlight?:
          | T
          | {
              text?: T;
              id?: T;
            };
        subheading?: T;
        cta1_Text?: T;
        cta2_Text?: T;
        backgroundImage?: T;
      };
  course_hero?:
    | T
    | {
        course_hero_eyebrow?: T;
        course_hero_heading?: T;
        highlight?:
          | T
          | {
              text?: T;
              id?: T;
            };
        course_hero_subheading?: T;
        course_hero_cta1_Text?: T;
        course_hero_cta2_Text?: T;
      };
  logoCarousel?:
    | T
    | {
        enabled?: T;
        logos?:
          | T
          | {
              heading?: T;
              subheading?: T;
              logo?: T;
              id?: T;
            };
      };
  features?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        highlight?:
          | T
          | {
              text?: T;
              id?: T;
            };
        subheading?: T;
        features?:
          | T
          | {
              heading?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  how_it_works?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        highlight?:
          | T
          | {
              text?: T;
              id?: T;
            };
        subheading?: T;
        how_it_works?:
          | T
          | {
              heading?: T;
              subheading?: T;
              description?: T;
              btn_text?: T;
              image?: T;
              id?: T;
            };
      };
  comparison_table?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        highlight?:
          | T
          | {
              text?: T;
              id?: T;
            };
        subheading?: T;
        comparison?:
          | T
          | {
              text?: T;
              id?: T;
            };
        coaching_center?:
          | T
          | {
              text?: T;
              id?: T;
            };
        clear_cutoff?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  reviews?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        highlight?:
          | T
          | {
              text?: T;
              id?: T;
            };
        subheading?: T;
        reviews?:
          | T
          | {
              name?: T;
              profile?: T;
              gender?: T;
              field?: T;
              review?: T;
              rating?: T;
              id?: T;
            };
      };
  faqs?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        highlight?:
          | T
          | {
              text?: T;
              id?: T;
            };
        subheading?: T;
        categories?:
          | T
          | {
              category?: T;
              id?: T;
            };
        faqs?:
          | T
          | {
              category?: T;
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  faqs_yesterday?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        highlight?:
          | T
          | {
              text?: T;
              id?: T;
            };
        subheading?: T;
        categories?:
          | T
          | {
              category?: T;
              id?: T;
            };
        faqs?:
          | T
          | {
              category?: T;
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}